version: "3"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: ["mongod", "--auth"]
    networks:
      - mongo_network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "${ME_PORT}:8081"
    environment:
      # Connection of User to Mongo Express
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}

      # Connection of Mongo Express to Mongo DB
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}

      # Admin access settings
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      
      # Let's encrypt settings
      VIRTUAL_HOST: ${MONGO_EXPRESS_SSL_DOMAIN}
      VIRTUAL_PORT: ${ME_PORT}
      LETSENCRYPT_HOST: ${MONGO_EXPRESS_SSL_DOMAIN}
      LETSENCRYPT_EMAIL: ${MONGO_EXPRESS_LETSENCRYPT_EMAIL}
    depends_on:
      - mongo
    networks:
      - mongo_network
      - proxy

networks:
  mongo_network:
  proxy:
    external:
      name: ${NGINX_PROXY_NETWORK}
