version: "3"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
    command: ["mongod", "--auth"]

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    env_file:
      - .env
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ROOT_PASSWORD}
      VIRTUAL_HOST: ${MONGO_EXPRESS_SSL_DOMAIN}
      VIRTUAL_PORT: ${MONGO_EXPRESS_PORT}
      LETSENCRYPT_HOST: ${MONGO_EXPRESS_SSL_DOMAIN}
      LETSENCRYPT_EMAIL: ${MONGO_EXPRESS_LETSENCRYPT_EMAIL}
    networks:
      - proxy

networks:
  proxy:
    external:
      name: nginx-proxy