version: "3"

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        volumes:
            - ./data:/data/db/
        env_file:
            - .env
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${ROOT_PASSWORD}
        command: ["mongod", "--auth"]
